### ISSUE TITLE
Option to generate sitemaps for dokkaHtml generated websites.

### ISSUE THREAD

**Issue by sureshg** [Kotlin/dokka#1305]
[Sitemaps](https://www.sitemaps.org/) is commonly used for making website searchable and discoverable.

```
Sitemaps are an easy way for webmasters to inform search engines about pages on their sites
that are available for crawling. In its simplest form, a Sitemap is an XML file that lists URLs for 
a site along with additional metadata about each URL (when it was last updated, how often it 
usually changes, and how important it is, relative to other URLs in the site) so that search engines 
can more intelligently crawl the site.
```

So this is a feature request to add an option to generate sitemaps for dokka generated html websites. 

https://support.google.com/webmasters/answer/183668?hl=en

**Comment by nathanfallet** [comment]
Actually I made [an external GitHub Actions](https://github.com/marketplace/actions/github-pages-sitemap-generator) do generate the sitemap before uploading to GitHub Pages:

```yaml
- name: Generate sitemap
  uses: guimauvedigital/generate-sitemap@v1
  with:
    base_url: "https://kdriver.dev"
    output_path: "build/docs/sitemap.xml"
    input_dir: "build/docs"
```

`build/docs` is the folder where I copy the generated Dokka files and other custom markdown files I want to deploy on my website.
