### ISSUE TITLE
How to merge documentation from several MPP modules

### ISSUE THREAD

**Issue by wakaztahir** [Kotlin/dokka#2378]
**Question**
Related to this [Your question](https://github.com/Kotlin/dokka/issues/776) , I have tried this but it doesn't seem to work plus since I am using kotlin gradle script I can't find multiplatform configuration block 

Root Gradle Build File

```kotlin
plugins {
    id("org.jetbrains.dokka") version BuildConfig.Info.DokkaVersion
}

tasks.withType<DokkaMultiModuleTask>(){
    outputDirectory.set(rootProject.file("docs/api"))
}
```

For subproject I needed dokka to generate documentation for , I have added dokka plugin without the version in the plugins block
and it doesn't give the error on my windows machine when run from intellij and generates the documentation but on Github Actions Workflow it gives this error

```
Execution failed for task ':dokkaHtmlMultiModule'.
    The DokkaMultiModuleTask_Decorated :dokkaHtmlMultiModule could not find any registered child task. 
    child tasks: [:android:dokkaHtmlPartial, :common:dokkaHtmlPartial, :desktop:dokkaHtmlPartial, :mapper:dokkaHtmlPartial]
    
    Please make sure to apply the dokka plugin to all included (sub)-projects individually e.g.:
    
    // subproject build.gradle.kts
    plugins {
        id("org.jetbrains.dokka")
    }
     
    or 
    
    // parent build.gradle.kts
    subprojects {
 Task :dokkaHtmlMultiModule FAILED
        plugins.apply("org.jetbrains.dokka")
    }
```

**Installation**
- Operating system: Windows
- Build tool: Gradle 
- Dokka version: 1.6.10

**Comment by wakaztahir** [comment]
Gihub Actions Workflow File

```yaml
name: MKDocs
on:
  push:
    branches:
      - master
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'adopt'

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install Dependencies
        run: pip install mkdocs-material

      - name: Generate Docs
        run: |
          chmod +x ./docs.sh
          chmod +x ./gradlew
          ./docs.sh

```
