### ISSUE TITLE
Configurable github pages theme

### ISSUE THREAD

**Issue by jacekgajek** [Kotlin/dokka#2423]
Currently, if deployment of documentation is done with github action, like this:
```
      - name: Deploy API documentation to Github Pages
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: ./build/dokka/jekyll
```
then the github theme is reset, becuase whole branch is purged.

It would be nice if the theme was configurable in gradle build script, like so
```
tasks.dokkaJekyll.configure {
    dokkaSourceSets {
        configureEach {
            theme.set("jekyll-theme-cayman")
        }
    }
}
```
Alternatively there could be a way to just include a file in the root of the repository.

In this case it would be a `_config.yml` file with contents
```
theme: jekyll-theme-cayman
```
which is created by github when theme is changed in settings.

#### Workaround

```
tasks.dokkaJekyll.configure {
    //    
    // (...)
    //
    finalizedBy("configureGhPages")
}

tasks.register<Copy>("configureGhPages") {
    from(layout.projectDirectory.dir(".github/hgpages"))
    into(layout.buildDirectory.dir("dokka/jekyll"))
}

```
And then add a file `.github/ghpages/_config.yml` with the following content:
```
theme: jekyll-theme-cayman
```
